# Generated by Django 5.2.17 on 2026-08-26 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('cad_source', 'CAD source'), ('cad_preview', 'CAD preview')], max_length=32)),
                ('classification', models.CharField(default='public_demo', max_length=32)),
                ('created_by', models.CharField(default='demo-user', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('original_filename', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=128)),
                ('format', models.CharField(max_length=16)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('source_system', models.CharField(default='upload', max_length=64)),
                ('classification', models.CharField(default='public_demo', max_length=32)),
                ('malware_status', models.CharField(choices=[('basic_screened', 'Basic screening passed'), ('not_scanned', 'Not scanned')], default='not_scanned', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='platform_core.artifact')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='platform_core.artifactversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CADModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cad_format', models.CharField(max_length=16)),
                ('unit_system', models.CharField(default='unknown', max_length=32)),
                ('parser_name', models.CharField(blank=True, max_length=128)),
                ('parser_version', models.CharField(blank=True, max_length=64)),
                ('geometry_status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('bounding_box', models.JSONField(default=dict)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('surface_area', models.FloatField(blank=True, null=True)),
                ('face_count', models.PositiveIntegerField(blank=True, null=True)),
                ('edge_count', models.PositiveIntegerField(blank=True, null=True)),
                ('surface_type_histogram', models.JSONField(default=dict)),
                ('quality_flags', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cad_model', to='platform_core.artifactversion')),
                ('preview_artifact_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preview_for_cad_models', to='platform_core.artifactversion')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability_id', models.CharField(max_length=128)),
                ('capability_version', models.CharField(default='1.0.0', max_length=32)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancel_requested', 'Cancel requested'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='queued', max_length=24)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('resource_class', models.CharField(default='cad', max_length=32)),
                ('queue', models.CharField(default='cad', max_length=64)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('result_ref', models.CharField(blank=True, max_length=255)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(default='queued', max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_artifact_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_jobs', to='platform_core.artifactversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(blank=True, max_length=24)),
                ('to_state', models.CharField(max_length=24)),
                ('stage', models.CharField(max_length=64)),
                ('progress', models.PositiveSmallIntegerField()),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='platform_core.job')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineageEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('derived_from', 'Derived from')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_artifact_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineage_out', to='platform_core.artifactversion')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineage_edges', to='platform_core.job')),
                ('to_artifact_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineage_in', to='platform_core.artifactversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='artifactversion',
            index=models.Index(fields=['sha256'], name='artifact_sha256_idx'),
        ),
        migrations.AddConstraint(
            model_name='artifactversion',
            constraint=models.UniqueConstraint(fields=('artifact', 'version_number'), name='unique_artifact_version_number'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['state', 'created_at'], name='job_state_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='lineageedge',
            constraint=models.UniqueConstraint(fields=('from_artifact_version', 'to_artifact_version', 'relationship'), name='unique_lineage_edge'),
        ),
    ]
