# Generated by Django 5.2.17 on 2026-08-26 02:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0002_similarity_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=128)),
                ('actor_id', models.CharField(max_length=128)),
                ('target_refs', models.JSONField(default=list)),
                ('detail', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('NOT_APPLICABLE', 'Not applicable'), ('NOT_EVALUATED', 'Not evaluated'), ('ERROR', 'Error')], max_length=24)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('limit_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=32)),
                ('severity', models.CharField(max_length=16)),
                ('risk_type', models.CharField(max_length=64)),
                ('geometry_location', models.JSONField(default=dict)),
                ('evidence_refs', models.JSONField(default=list)),
                ('quality_flags', models.JSONField(default=list)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rule_version__sort_order', 'rule_version__rule_id'],
            },
        ),
        migrations.CreateModel(
            name='RuleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_key', models.CharField(max_length=128, unique=True)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(default='approved_demo', max_length=32)),
                ('product_scope', models.JSONField(default=list)),
                ('material_scope', models.JSONField(default=list)),
                ('owner', models.CharField(max_length=128)),
                ('approved_by', models.CharField(max_length=128)),
                ('ruleset_checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waived', 'Waived')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('decided_by', models.CharField(max_length=128)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='platform_core.reviewfinding')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.JSONField(default=dict)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('geometry_engine_version', models.CharField(max_length=128)),
                ('review_status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('result_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cad_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_runs', to='platform_core.cadmodel')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='design_review', to='platform_core.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_runs', to='platform_core.ruleprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reviewfinding',
            name='review_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='platform_core.reviewrun'),
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(max_length=64)),
                ('rule_version', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evaluator', models.CharField(max_length=64)),
                ('applicability', models.JSONField(default=dict)),
                ('parameters', models.JSONField(default=dict)),
                ('operator', models.CharField(max_length=16)),
                ('limit_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=32)),
                ('tolerance', models.FloatField(default=0)),
                ('severity', models.CharField(max_length=16)),
                ('risk_type', models.CharField(max_length=64)),
                ('recommendation', models.TextField()),
                ('reference', models.JSONField(default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='platform_core.ruleprofile')),
            ],
            options={
                'ordering': ['sort_order', 'rule_id'],
            },
        ),
        migrations.AddField(
            model_name='reviewfinding',
            name='rule_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='platform_core.ruleversion'),
        ),
        migrations.AddConstraint(
            model_name='ruleversion',
            constraint=models.UniqueConstraint(fields=('profile', 'rule_id', 'rule_version'), name='unique_rule_profile_version'),
        ),
        migrations.AddConstraint(
            model_name='reviewfinding',
            constraint=models.UniqueConstraint(fields=('review_run', 'rule_version'), name='unique_review_finding'),
        ),
    ]
