# Generated by Django 5.2.17 on 2026-08-26 02:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0003_auditevent_reviewfinding_ruleprofile_reviewdecision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('principal_scopes', models.JSONField(default=list)),
                ('filters', models.JSONField(default=dict)),
                ('retrieval_config', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('abstained', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('cad_source', 'CAD source'), ('cad_preview', 'CAD preview'), ('knowledge_source', 'Knowledge source')], max_length=32),
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=64)),
                ('authority_level', models.CharField(default='demo', max_length=32)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(max_length=128)),
                ('classification', models.CharField(default='public_demo', max_length=32)),
                ('acl_scopes', models.JSONField(default=list)),
                ('language', models.CharField(default='en', max_length=16)),
                ('parser_version', models.CharField(default='plain-text@1.0.0', max_length=64)),
                ('chunker_version', models.CharField(default='section-paragraph@1.0.0', max_length=64)),
                ('ingestion_status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('indexed', 'Indexed'), ('quarantined', 'Quarantined'), ('failed', 'Failed'), ('obsolete', 'Obsolete')], default='queued', max_length=24)),
                ('injection_scan_status', models.CharField(default='pending', max_length=24)),
                ('injection_findings', models.JSONField(default=list)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_document', to='platform_core.artifactversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('text_hash', models.CharField(max_length=64)),
                ('locator', models.JSONField(default=dict)),
                ('embedding_model', models.CharField(default='feature-hash-demo@1.0.0', max_length=128)),
                ('embedding_dimension', models.PositiveSmallIntegerField(default=64)),
                ('embedding', models.JSONField(default=list)),
                ('language', models.CharField(default='en', max_length=16)),
                ('injection_scan_status', models.CharField(default='clear', max_length=24)),
                ('index_status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chunks', to='platform_core.knowledgedocument')),
            ],
            options={
                'ordering': ['ordinal'],
                'indexes': [models.Index(fields=['text_hash'], name='knowledge_text_hash_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'ordinal'), name='unique_knowledge_chunk_ordinal')],
            },
        ),
    ]
