# Generated by Django 5.2.17 on 2026-08-26 03:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0004_knowledgesearch_alter_artifact_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCaseSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_snapshot', models.JSONField(default=dict)),
                ('scoring_profile_version', models.CharField(max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('abstained', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrialCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_code', models.CharField(max_length=64, unique=True)),
                ('connector_key', models.CharField(max_length=64)),
                ('source_record_id', models.CharField(max_length=128)),
                ('source_version', models.CharField(max_length=64)),
                ('source_hash', models.CharField(max_length=64)),
                ('mapping_version', models.CharField(max_length=64)),
                ('classification', models.CharField(default='public_demo', max_length=32)),
                ('acl_scopes', models.JSONField(default=list)),
                ('mold_revision_ref', models.CharField(max_length=128)),
                ('part_revision_ref', models.CharField(max_length=128)),
                ('machine_code', models.CharField(max_length=64)),
                ('material_code', models.CharField(max_length=64)),
                ('material_lot', models.CharField(blank=True, max_length=64)),
                ('product_type', models.CharField(max_length=128)),
                ('operator_ref', models.CharField(default='synthetic-operator', max_length=128)),
                ('purpose', models.CharField(max_length=255)),
                ('outcome', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField()),
                ('data_quality', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['case_code'],
                'indexes': [models.Index(fields=['material_code', 'machine_code'], name='trial_material_machine_idx')],
                'constraints': [models.UniqueConstraint(fields=('connector_key', 'source_record_id', 'source_version'), name='unique_trial_source_version')],
            },
        ),
        migrations.CreateModel(
            name='ProcessRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_number', models.PositiveSmallIntegerField()),
                ('cycle_start', models.PositiveIntegerField(blank=True, null=True)),
                ('cycle_end', models.PositiveIntegerField(blank=True, null=True)),
                ('environment', models.JSONField(default=dict)),
                ('result', models.CharField(max_length=64)),
                ('data_quality', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='platform_core.trialcase')),
            ],
            options={
                'ordering': ['run_number'],
            },
        ),
        migrations.CreateModel(
            name='ProcessParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_code', models.CharField(max_length=64)),
                ('raw_name', models.CharField(max_length=128)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=32)),
                ('value_kind', models.CharField(choices=[('setpoint', 'Setpoint'), ('actual', 'Actual')], max_length=16)),
                ('sampling_method', models.CharField(max_length=64)),
                ('sampled_at', models.DateTimeField(blank=True, null=True)),
                ('process_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='platform_core.processrun')),
            ],
            options={
                'ordering': ['canonical_code', 'value_kind'],
                'constraints': [models.UniqueConstraint(fields=('process_run', 'canonical_code', 'value_kind'), name='unique_run_parameter_kind')],
            },
        ),
        migrations.CreateModel(
            name='DefectObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('defect_code', models.CharField(max_length=64)),
                ('severity', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=128)),
                ('quantity_rate', models.FloatField(blank=True, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=32)),
                ('inspection_method', models.CharField(max_length=128)),
                ('evidence_refs', models.JSONField(default=list)),
                ('process_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='platform_core.processrun')),
            ],
            options={
                'ordering': ['defect_code'],
                'indexes': [models.Index(fields=['defect_code'], name='trial_defect_code_idx')],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_code', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('before_values', models.JSONField(default=dict)),
                ('after_values', models.JSONField(default=dict)),
                ('rationale_source', models.JSONField(default=dict)),
                ('approved_by', models.CharField(max_length=128)),
                ('executed', models.BooleanField(default=False)),
                ('observed_outcome', models.JSONField(default=dict)),
                ('expected_effect', models.TextField()),
                ('stop_condition', models.TextField()),
                ('evidence_refs', models.JSONField(default=list)),
                ('process_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='platform_core.processrun')),
            ],
            options={
                'ordering': ['action_code'],
                'constraints': [models.UniqueConstraint(fields=('process_run', 'action_code'), name='unique_run_corrective_action')],
            },
        ),
        migrations.AddConstraint(
            model_name='processrun',
            constraint=models.UniqueConstraint(fields=('trial', 'run_number'), name='unique_trial_process_run'),
        ),
    ]
