# Generated by Django 5.2.17 on 2026-08-26 04:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0005_processcasesearch_trialcase_processrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAERun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_code', models.CharField(max_length=64)),
                ('solver_name', models.CharField(max_length=128)),
                ('solver_version', models.CharField(max_length=64)),
                ('mesh_artifact_ref', models.CharField(max_length=255)),
                ('mesh_checksum', models.CharField(max_length=64)),
                ('material_model_code', models.CharField(max_length=128)),
                ('boundary_settings', models.JSONField(default=dict)),
                ('process_settings', models.JSONField(default=dict)),
                ('unit_system', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('incomplete', 'Incomplete')], max_length=24)),
                ('input_hash', models.CharField(max_length=64)),
                ('data_quality', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['run_code'],
            },
        ),
        migrations.CreateModel(
            name='CAEComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compatibility_profile_version', models.CharField(max_length=64)),
                ('request_snapshot', models.JSONField(default=dict)),
                ('compatible', models.BooleanField(default=False)),
                ('incompatibilities', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseline_comparisons', to='platform_core.caerun')),
                ('candidate_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_comparisons', to='platform_core.caerun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CAEStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_code', models.CharField(max_length=64, unique=True)),
                ('connector_key', models.CharField(max_length=64)),
                ('integration_level', models.CharField(max_length=64)),
                ('source_record_id', models.CharField(max_length=128)),
                ('source_version', models.CharField(max_length=64)),
                ('source_hash', models.CharField(max_length=64)),
                ('mapping_version', models.CharField(max_length=64)),
                ('solver_name', models.CharField(max_length=128)),
                ('product_ref', models.CharField(max_length=128)),
                ('mold_revision_ref', models.CharField(max_length=128)),
                ('material_model_code', models.CharField(max_length=128)),
                ('mesh_family', models.CharField(max_length=128)),
                ('objective', models.TextField()),
                ('owner', models.CharField(max_length=128)),
                ('classification', models.CharField(default='public_demo', max_length=32)),
                ('acl_scopes', models.JSONField(default=list)),
                ('data_quality', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['study_code'],
                'constraints': [models.UniqueConstraint(fields=('connector_key', 'source_record_id', 'source_version'), name='unique_cae_study_source_version')],
            },
        ),
        migrations.AddField(
            model_name='caerun',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='platform_core.caestudy'),
        ),
        migrations.CreateModel(
            name='CAEResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_code', models.CharField(max_length=128)),
                ('result_type', models.CharField(choices=[('scalar', 'Scalar'), ('region_count', 'Region count')], max_length=32)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=32)),
                ('location', models.JSONField(default=dict)),
                ('field_summary', models.JSONField(default=dict)),
                ('quality_flags', models.JSONField(default=list)),
                ('parser_name', models.CharField(max_length=128)),
                ('parser_version', models.CharField(max_length=64)),
                ('source_locator', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='platform_core.caerun')),
            ],
            options={
                'ordering': ['metric_code'],
                'indexes': [models.Index(fields=['metric_code'], name='cae_metric_code_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'metric_code'), name='unique_cae_run_metric')],
            },
        ),
        migrations.AddConstraint(
            model_name='caerun',
            constraint=models.UniqueConstraint(fields=('study', 'run_code'), name='unique_cae_study_run'),
        ),
    ]
