# Generated by Django 5.2.17 on 2026-08-26 05:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0006_caerun_caecomparison_caestudy_caerun_study_caeresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('cad_source', 'CAD source'), ('cad_preview', 'CAD preview'), ('knowledge_source', 'Knowledge source'), ('hmi_source', 'HMI source image'), ('hmi_export', 'HMI spreadsheet export')], max_length=32),
        ),
        migrations.CreateModel(
            name='HMIExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_key', models.CharField(max_length=128)),
                ('profile_version', models.CharField(max_length=32)),
                ('extractor_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=24)),
                ('image_width', models.PositiveIntegerField()),
                ('image_height', models.PositiveIntegerField()),
                ('preprocessing', models.JSONField(default=dict)),
                ('review_status', models.CharField(default='pending_review', max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_artifact_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hmi_extraction', to='platform_core.artifactversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HMIExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_version', models.CharField(max_length=64)),
                ('reviewed_snapshot_hash', models.CharField(max_length=64)),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hmi_export', to='platform_core.artifactversion')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='platform_core.hmiextraction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HMIExtractedField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter_code', models.CharField(max_length=64)),
                ('display_label', models.CharField(max_length=128)),
                ('raw_text', models.CharField(blank=True, max_length=128)),
                ('normalized_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=32)),
                ('confidence', models.FloatField()),
                ('source_region', models.JSONField(default=dict)),
                ('validation_status', models.CharField(max_length=32)),
                ('review_status', models.CharField(choices=[('not_required', 'Not required'), ('needs_review', 'Needs review'), ('confirmed', 'Confirmed'), ('corrected', 'Corrected'), ('rejected', 'Rejected')], max_length=24)),
                ('reviewer_value', models.FloatField(blank=True, null=True)),
                ('reviewer_unit', models.CharField(blank=True, max_length=32)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='platform_core.hmiextraction')),
            ],
            options={
                'ordering': ['parameter_code'],
                'constraints': [models.UniqueConstraint(fields=('extraction', 'parameter_code'), name='unique_hmi_extraction_field')],
            },
        ),
    ]
