# Generated by Django 5.2.17 on 2026-08-29 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_demo_registry(apps, schema_editor):
    AccessRole = apps.get_model("platform_core", "AccessRole")
    Artifact = apps.get_model("platform_core", "Artifact")
    DataScope = apps.get_model("platform_core", "DataScope")
    Mold = apps.get_model("platform_core", "Mold")
    MoldRevision = apps.get_model("platform_core", "MoldRevision")
    ProductPart = apps.get_model("platform_core", "ProductPart")
    Project = apps.get_model("platform_core", "Project")

    scope = DataScope.objects.get(code="public-demo")
    project, _ = Project.objects.get_or_create(
        scope=scope,
        code="DEMO-CAD",
        defaults={
            "name": "Curated CAD Demonstration",
            "description": "Synthetic mold registry for the curated CAD golden dataset.",
            "created_by": "system:migration",
            "updated_by": "system:migration",
        },
    )
    part, _ = ProductPart.objects.get_or_create(
        project=project,
        part_number="DEMO-PART",
        defaults={
            "name": "Synthetic demonstration part family",
            "product_type": "housing",
            "material_code": "ABS-GENERAL",
            "created_by": "system:migration",
            "updated_by": "system:migration",
        },
    )
    artifacts = Artifact.objects.filter(kind="cad_source", dataset_id="curated-cad-demo-v1").order_by(
        "created_at", "id"
    )
    for index, artifact in enumerate(artifacts, start=1):
        mold, _ = Mold.objects.get_or_create(
            project=project,
            mold_code=f"DEMO-MOLD-{index:03d}",
            defaults={
                "product_part": part,
                "name": artifact.name,
                "created_by": "system:migration",
                "updated_by": "system:migration",
            },
        )
        revision, _ = MoldRevision.objects.get_or_create(
            mold=mold,
            revision_code="A",
            defaults={
                "status": "released",
                "change_summary": "Migrated curated CAD fixture",
                "source_system": "curated_demo_fixture",
                "source_revision_id": str(artifact.id),
                "created_by": "system:migration",
                "updated_by": "system:migration",
            },
        )
        artifact.mold_revision_id = revision.id
        artifact.quality_status = "validated"
        artifact.save(update_fields=["mold_revision", "quality_status"])

    for role in AccessRole.objects.all():
        permissions = list(role.permissions)
        if "registry:read" not in permissions:
            permissions.append("registry:read")
        if role.code in {"mold_engineer", "data_steward", "platform_admin"}:
            if "registry:manage" not in permissions:
                permissions.append("registry:manage")
        role.permissions = permissions
        role.save(update_fields=["permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0009_governed_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mold_code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('mold_type', models.CharField(default='injection', max_length=64)),
                ('cavity_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('archived', 'Archived')], default='active', max_length=16)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('created_by', models.CharField(default='system', max_length=128)),
                ('updated_by', models.CharField(default='system', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project__code', 'mold_code'],
            },
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(blank=True, max_length=128)),
                ('material_code', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('created_by', models.CharField(default='system', max_length=128)),
                ('updated_by', models.CharField(default='system', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project__code', 'part_number'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='artifact',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='lifecycle_status',
            field=models.CharField(default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='artifact',
            name='quality_status',
            field=models.CharField(default='pending', max_length=24),
        ),
        migrations.CreateModel(
            name='MoldRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('change_summary', models.TextField(blank=True)),
                ('source_system', models.CharField(default='platform_demo', max_length=64)),
                ('source_revision_id', models.CharField(blank=True, max_length=128)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(default='system', max_length=128)),
                ('updated_by', models.CharField(default='system', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='platform_core.mold')),
            ],
            options={
                'ordering': ['mold__mold_code', 'revision_code'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='mold_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='platform_core.moldrevision'),
        ),
        migrations.AddField(
            model_name='mold',
            name='product_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='molds', to='platform_core.productpart'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('classification', models.CharField(default='public_demo', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('created_by', models.CharField(default='system', max_length=128)),
                ('updated_by', models.CharField(default='system', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='platform_core.datascope')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='productpart',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='platform_core.project'),
        ),
        migrations.AddField(
            model_name='mold',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='molds', to='platform_core.project'),
        ),
        migrations.AddConstraint(
            model_name='moldrevision',
            constraint=models.UniqueConstraint(fields=('mold', 'revision_code'), name='unique_mold_revision_code'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='unique_project_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='productpart',
            constraint=models.UniqueConstraint(fields=('project', 'part_number'), name='unique_project_part_number'),
        ),
        migrations.AddConstraint(
            model_name='mold',
            constraint=models.UniqueConstraint(fields=('project', 'mold_code'), name='unique_project_mold_code'),
        ),
        migrations.RunPython(seed_demo_registry, migrations.RunPython.noop),
    ]
