# Generated by Django 5.2.17 on 2026-08-29 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


def add_governance_permissions(apps, schema_editor):
    AccessRole = apps.get_model("platform_core", "AccessRole")
    for role in AccessRole.objects.all():
        permissions = list(role.permissions)
        for permission in ("rules:read", "knowledge:read"):
            if permission not in permissions:
                permissions.append(permission)
        if role.code in {"rule_owner", "platform_admin"} and "rules:author" not in permissions:
            permissions.append("rules:author")
        if role.code in {"technical_reviewer", "approver", "platform_admin"}:
            if "rules:approve" not in permissions:
                permissions.append("rules:approve")
        if role.code in {"knowledge_curator", "data_steward", "platform_admin"}:
            if "knowledge:author" not in permissions:
                permissions.append("knowledge:author")
        if role.code in {"approver", "platform_admin"}:
            if "knowledge:approve" not in permissions:
                permissions.append("knowledge:approve")
        role.permissions = permissions
        role.save(update_fields=["permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0010_mold_registry_and_governed_artifacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='approved_by',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='document_key',
            field=models.CharField(default=uuid.uuid4, max_length=128),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='publication_status',
            field=models.CharField(default='published', max_length=24),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='platform_core.knowledgedocument'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ruleprofile',
            name='change_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ruleprofile',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruleprofile',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruleprofile',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ruleprofile',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ruleprofile',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ruleprofile',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('in_review', 'In review'), ('approved', 'Approved'), ('published', 'Published'), ('retired', 'Retired')], default='published', max_length=16),
        ),
        migrations.AlterField(
            model_name='ruleprofile',
            name='profile_key',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.UniqueConstraint(fields=('document_key', 'version_number'), name='unique_knowledge_document_version'),
        ),
        migrations.AddConstraint(
            model_name='ruleprofile',
            constraint=models.UniqueConstraint(fields=('profile_key', 'version'), name='unique_rule_profile_key_version'),
        ),
        migrations.RunPython(add_governance_permissions, migrations.RunPython.noop),
    ]
