# Generated by Django 5.2.17 on 2026-08-29 05:42

import django.db.models.deletion
import hashlib
import json
import uuid
from django.db import migrations, models
from django.utils import timezone


HMI_FIELD_SPECS = [
    {"code": "injection_pressure_mpa", "label": "Injection Pressure", "unit": "MPa", "minimum": 20, "maximum": 300, "region": [0.55, 0.16, 0.35, 0.1]},
    {"code": "injection_speed_mm_s", "label": "Injection Speed", "unit": "mm/s", "minimum": 1, "maximum": 500, "region": [0.55, 0.34, 0.35, 0.1]},
    {"code": "holding_pressure_mpa", "label": "Holding Pressure", "unit": "MPa", "minimum": 5, "maximum": 250, "region": [0.55, 0.52, 0.35, 0.1]},
    {"code": "cooling_time_s", "label": "Cooling Time", "unit": "s", "minimum": 0, "maximum": 300, "region": [0.55, 0.7, 0.35, 0.1]},
]


def seed_engineering_data_governance(apps, schema_editor):
    AccessRole = apps.get_model("platform_core", "AccessRole")
    HMIExtraction = apps.get_model("platform_core", "HMIExtraction")
    HMIProfileVersion = apps.get_model("platform_core", "HMIProfileVersion")
    TrialCase = apps.get_model("platform_core", "TrialCase")

    for role in AccessRole.objects.all():
        permissions = list(role.permissions)
        if "engineering-data:read" not in permissions:
            permissions.append("engineering-data:read")
        if role.code in {
            "mold_engineer",
            "data_editor",
            "data_steward",
            "platform_admin",
        } and "engineering-data:manage" not in permissions:
            permissions.append("engineering-data:manage")
        role.permissions = permissions
        role.save(update_fields=["permissions"])

    checksum = hashlib.sha256(json.dumps(HMI_FIELD_SPECS, sort_keys=True).encode()).hexdigest()
    profile, _ = HMIProfileVersion.objects.get_or_create(
        profile_key="demo-generic-injection",
        version="1.0",
        defaults={
            "status": "published",
            "field_specs": HMI_FIELD_SPECS,
            "profile_checksum": checksum,
            "change_summary": "Synthetic fixed-layout seven-segment Demo profile",
            "created_by": "system:demo",
            "published_by": "system:demo",
            "published_at": timezone.now(),
        },
    )
    HMIExtraction.objects.filter(
        profile_definition__isnull=True,
        profile_key="demo-generic-injection",
        profile_version="1.0",
    ).update(profile_definition=profile)
    TrialCase.objects.filter(closed_at__isnull=True).update(closed_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0011_governed_rule_and_knowledge_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='caestudy',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='caestudy',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caestudy',
            name='lifecycle_status',
            field=models.CharField(default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='caestudy',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='caestudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trialcase',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='trialcase',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialcase',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('archived', 'Archived')], default='closed', max_length=16),
        ),
        migrations.AddField(
            model_name='trialcase',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trialcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='HMICorrectionDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=16)),
                ('before_value', models.JSONField(default=dict)),
                ('after_value', models.JSONField(default=dict)),
                ('reason', models.CharField(max_length=512)),
                ('decided_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_decisions', to='platform_core.hmiextractedfield')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HMIProfileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_key', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('field_specs', models.JSONField(default=list)),
                ('profile_checksum', models.CharField(max_length=64)),
                ('change_summary', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=128)),
                ('published_by', models.CharField(blank=True, max_length=128)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['profile_key', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('profile_key', 'version'), name='unique_hmi_profile_version')],
            },
        ),
        migrations.AddField(
            model_name='hmiextraction',
            name='profile_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extractions', to='platform_core.hmiprofileversion'),
        ),
        migrations.CreateModel(
            name='MasterDataMappingBacklog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_domain', models.CharField(max_length=64)),
                ('source_record_ref', models.CharField(max_length=128)),
                ('field_name', models.CharField(max_length=64)),
                ('raw_value', models.CharField(max_length=255)),
                ('target_kind', models.CharField(choices=[('dataset', 'Dataset'), ('product_type', 'Product type'), ('material', 'Material'), ('machine', 'Machine'), ('defect', 'Defect'), ('location', 'Location'), ('unit', 'Unit')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('mapped', 'Mapped'), ('ignored', 'Ignored')], default='pending', max_length=16)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'constraints': [models.UniqueConstraint(fields=('source_domain', 'field_name', 'raw_value', 'target_kind'), name='unique_pending_mapping_value')],
            },
        ),
        migrations.CreateModel(
            name='TrialCorrectionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('before_values', models.JSONField(default=dict)),
                ('after_values', models.JSONField(default=dict)),
                ('reason', models.CharField(max_length=512)),
                ('corrected_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='platform_core.trialcase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(seed_engineering_data_governance, migrations.RunPython.noop),
    ]
