# Generated by Django 5.2.17 on 2026-08-30 02:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


def add_ingestion_permissions(apps, schema_editor):
    role_model = apps.get_model("platform_core", "AccessRole")
    additions = {
        "platform_admin": [
            "ingestion:read",
            "ingestion:create",
            "ingestion:validate",
            "ingestion:commit",
            "ingestion:cancel",
            "ingestion:template-manage",
        ],
        "data_steward": [
            "ingestion:read",
            "ingestion:create",
            "ingestion:validate",
            "ingestion:commit",
            "ingestion:cancel",
        ],
    }
    for code, permissions in additions.items():
        role = role_model.objects.filter(code=code).first()
        if role is None:
            continue
        merged = list(role.permissions)
        for permission in permissions:
            if permission not in merged:
                merged.append(permission)
        role.permissions = merged
        role.save(update_fields=["permissions"])


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0016_rule_resolution_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkimportbatch",
            name="classification",
            field=models.CharField(default="public_demo", max_length=32),
        ),
        migrations.AddField(
            model_name="bulkimportbatch",
            name="job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingestion_batch",
                to="platform_core.job",
            ),
        ),
        migrations.AddField(
            model_name="bulkimportbatch",
            name="mapping_version",
            field=models.CharField(default="1.0", max_length=32),
        ),
        migrations.AddField(
            model_name="bulkimportbatch",
            name="schema_version",
            field=models.CharField(default="1.0", max_length=32),
        ),
        migrations.AddField(
            model_name="bulkimportbatch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="kind",
            field=models.CharField(
                choices=[
                    ("cad_source", "CAD source"),
                    ("cad_preview", "CAD preview"),
                    ("knowledge_source", "Knowledge source"),
                    ("hmi_source", "HMI source image"),
                    ("hmi_export", "HMI spreadsheet export"),
                    ("import_source", "Ingestion source file"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="bulkimportbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("uploaded", "Uploaded"),
                    ("mapping_required", "Mapping required"),
                    ("validating", "Validating"),
                    ("validation_failed", "Validation failed"),
                    ("validated", "Validated"),
                    ("queued", "Queued"),
                    ("committing", "Committing"),
                    ("committed", "Committed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="IngestionIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("row_number", models.PositiveIntegerField(blank=True, null=True)),
                ("field_name", models.CharField(blank=True, max_length=128)),
                ("code", models.CharField(max_length=128)),
                ("message", models.CharField(max_length=512)),
                ("raw_value", models.JSONField(blank=True, null=True)),
                ("suggestion", models.CharField(blank=True, max_length=512)),
                (
                    "severity",
                    models.CharField(
                        choices=[("blocking", "Blocking"), ("warning", "Warning")],
                        default="blocking",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="platform_core.bulkimportbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngestionSourceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                ("mime_type", models.CharField(max_length=128)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("screening", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_sources",
                        to="platform_core.artifactversion",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_files",
                        to="platform_core.bulkimportbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReconciliationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("balanced", models.BooleanField(default=False)),
                ("report_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_report",
                        to="platform_core.bulkimportbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngestionRecordResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(blank=True, max_length=128)),
                ("detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_results",
                        to="platform_core.bulkimportbatch",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "row_number"), name="unique_ingestion_row_result"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MappingProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("domain", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("version", models.CharField(default="1.0", max_length=32)),
                ("field_mapping", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapping_profiles",
                        to="platform_core.datascope",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "domain", "name", "version"),
                        name="unique_ingestion_mapping_version",
                    )
                ],
            },
        ),
        migrations.RunPython(add_ingestion_permissions, migrations.RunPython.noop),
    ]
