# Generated by Django 5.2.17 on 2026-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0023_hybrid_knowledge_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadmodel',
            name='brep_structure',
            field=models.JSONField(default=dict),
        ),
    ]
