# Generated by Django 5.2.17 on 2026-09-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0024_cad_brep_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceVerificationCache',
            fields=[
                ('slot', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
