from django.urls import path

from .engineering_data_views import (
    GovernedCAERunCreateView,
    GovernedCAEStudyDetailView,
    GovernedCAEStudyListView,
    GovernedProcessRunCreateView,
    GovernedTrialCaseDetailView,
    GovernedTrialCaseListView,
    HMIProfileActionView,
    HMIProfileDetailView,
    HMIProfileListCreateView,
)
from .enterprise_views import (
    BulkArchiveView,
    BulkImportDetailView,
    BulkImportListCreateView,
    EnterprisePolicyView,
)
from .governance_views import (
    KnowledgeDocumentWorkflowView,
    RuleProfileDetailView,
    RuleProfileDiffView,
    RuleProfileGovernanceListView,
    RuleProfileImpactPreviewView,
    RuleProfileValidationView,
    RuleProfileWorkflowView,
)
from .history_views import (
    AnalysisDetailView,
    AnalysisHistoryView,
    AuditDetailView,
    AuditExportView,
    AuditHistoryView,
    JobHistoryDetailView,
    JobHistoryView,
    LineageHistoryView,
)
from .identity_views import (
    AccountDetailView,
    AccountListCreateView,
    AccountStateView,
    CsrfTokenView,
    CurrentAccountView,
    IdentityCatalogView,
    LocalLoginView,
    LocalLogoutView,
    RoleAssignmentCreateRevokeView,
)
from .ingestion_views import (
    ImportTemplateView,
    IngestionCancelView,
    IngestionCommitView,
    IngestionDetailView,
    IngestionFileView,
    IngestionIssuesView,
    IngestionListCreateView,
    IngestionMappingView,
    IngestionReconciliationView,
    IngestionValidateView,
)
from .master_data_views import MasterDataDetailView, MasterDataListCreateView, MasterDataOptionsView
from .mold_planning_views import MoldPlanningResolutionPreviewView
from .registry_views import (
    ArtifactGovernanceView,
    MoldDetailView,
    MoldListCreateView,
    PartDetailView,
    PartListCreateView,
    ProjectDetailView,
    ProjectListCreateView,
    RevisionDetailView,
    RevisionListCreateView,
)
from .views import (
    ArtifactVersionDownloadView,
    AssistantCapabilitiesView,
    AssistantMessageView,
    CADArtifactDetailView,
    CADArtifactListCreateView,
    CAEComparisonDetailView,
    CAEComparisonListCreateView,
    CAEDemoFixtureView,
    DemoStatusView,
    DesignReviewDetailView,
    DesignReviewListCreateView,
    EngineeringCapabilitiesView,
    HMIDemoFixtureView,
    HMIExtractionBatchCreateView,
    HMIExtractionDetailView,
    HMIExtractionExportView,
    HMIExtractionListCreateView,
    HMIExtractionReviewView,
    JobDetailView,
    KnowledgeDocumentDetailView,
    KnowledgeDocumentListCreateView,
    KnowledgeSearchDetailView,
    KnowledgeSearchListCreateView,
    LiveView,
    ProcessCaseSearchDetailView,
    ProcessCaseSearchListCreateView,
    ProcessTrialDemoFixtureView,
    ReadyView,
    ReviewFindingDecisionCreateView,
    SecurityPreflightView,
    SimilaritySearchDetailView,
    SimilaritySearchListCreateView,
    SystemInfoView,
)

app_name = "platform_core"

urlpatterns = [
    path("auth/csrf", CsrfTokenView.as_view(), name="auth-csrf"),
    path("auth/login", LocalLoginView.as_view(), name="auth-login"),
    path("auth/logout", LocalLogoutView.as_view(), name="auth-logout"),
    path("auth/me", CurrentAccountView.as_view(), name="auth-me"),
    path("admin/users", AccountListCreateView.as_view(), name="admin-user-list-create"),
    path("admin/users/<uuid:account_id>", AccountDetailView.as_view(), name="admin-user-detail"),
    path(
        "admin/users/<uuid:account_id>/<str:action>",
        AccountStateView.as_view(),
        name="admin-user-state",
    ),
    path("admin/identity-catalog", IdentityCatalogView.as_view(), name="identity-catalog"),
    path("master-data/options", MasterDataOptionsView.as_view(), name="master-data-options"),
    path("master-data", MasterDataListCreateView.as_view(), name="master-data-list-create"),
    path("master-data/<uuid:item_id>", MasterDataDetailView.as_view(), name="master-data-detail"),
    path(
        "mold-plans/resolution-preview",
        MoldPlanningResolutionPreviewView.as_view(),
        name="mold-planning-resolution-preview",
    ),
    path("registry/projects", ProjectListCreateView.as_view(), name="registry-project-list"),
    path(
        "registry/projects/<uuid:project_id>",
        ProjectDetailView.as_view(),
        name="registry-project-detail",
    ),
    path("registry/parts", PartListCreateView.as_view(), name="registry-part-list"),
    path("registry/parts/<uuid:part_id>", PartDetailView.as_view(), name="registry-part-detail"),
    path("registry/molds", MoldListCreateView.as_view(), name="registry-mold-list"),
    path("registry/molds/<uuid:mold_id>", MoldDetailView.as_view(), name="registry-mold-detail"),
    path("registry/revisions", RevisionListCreateView.as_view(), name="registry-revision-list"),
    path(
        "registry/revisions/<uuid:revision_id>",
        RevisionDetailView.as_view(),
        name="registry-revision-detail",
    ),
    path(
        "registry/artifacts/<uuid:artifact_id>",
        ArtifactGovernanceView.as_view(),
        name="registry-artifact-detail",
    ),
    path(
        "admin/role-assignments",
        RoleAssignmentCreateRevokeView.as_view(),
        name="role-assignment-create",
    ),
    path(
        "admin/role-assignments/<uuid:assignment_id>",
        RoleAssignmentCreateRevokeView.as_view(),
        name="role-assignment-revoke",
    ),
    path("health/live", LiveView.as_view(), name="health-live"),
    path("health/ready", ReadyView.as_view(), name="health-ready"),
    path("system/info", SystemInfoView.as_view(), name="system-info"),
    path(
        "engineering-capabilities",
        EngineeringCapabilitiesView.as_view(),
        name="engineering-capabilities",
    ),
    path("demo/status", DemoStatusView.as_view(), name="demo-status"),
    path("security/preflight", SecurityPreflightView.as_view(), name="security-preflight"),
    path("hmi/demo-fixture", HMIDemoFixtureView.as_view(), name="hmi-demo-fixture"),
    path(
        "hmi-extractions",
        HMIExtractionListCreateView.as_view(),
        name="hmi-extraction-list-create",
    ),
    path(
        "hmi-extractions/batch",
        HMIExtractionBatchCreateView.as_view(),
        name="hmi-extraction-batch-create",
    ),
    path(
        "hmi-extractions/<uuid:extraction_id>",
        HMIExtractionDetailView.as_view(),
        name="hmi-extraction-detail",
    ),
    path(
        "hmi-extractions/<uuid:extraction_id>/review",
        HMIExtractionReviewView.as_view(),
        name="hmi-extraction-review",
    ),
    path(
        "hmi-extractions/<uuid:extraction_id>/exports",
        HMIExtractionExportView.as_view(),
        name="hmi-extraction-export",
    ),
    path(
        "assistant/capabilities",
        AssistantCapabilitiesView.as_view(),
        name="assistant-capabilities",
    ),
    path("assistant/messages", AssistantMessageView.as_view(), name="assistant-messages"),
    path("cae/demo-fixtures", CAEDemoFixtureView.as_view(), name="cae-demo-fixtures"),
    path("cae-studies", GovernedCAEStudyListView.as_view(), name="cae-study-list"),
    path(
        "cae-studies/<uuid:study_id>",
        GovernedCAEStudyDetailView.as_view(),
        name="cae-study-detail",
    ),
    path(
        "cae-studies/<uuid:study_id>/runs",
        GovernedCAERunCreateView.as_view(),
        name="cae-run-create",
    ),
    path(
        "cae-comparisons",
        CAEComparisonListCreateView.as_view(),
        name="cae-comparison-list-create",
    ),
    path(
        "cae-comparisons/<uuid:comparison_id>",
        CAEComparisonDetailView.as_view(),
        name="cae-comparison-detail",
    ),
    path(
        "process-trial/demo-fixtures",
        ProcessTrialDemoFixtureView.as_view(),
        name="process-trial-demo-fixtures",
    ),
    path("trial-cases", GovernedTrialCaseListView.as_view(), name="trial-case-list"),
    path(
        "trial-cases/<uuid:trial_case_id>",
        GovernedTrialCaseDetailView.as_view(),
        name="trial-case-detail",
    ),
    path(
        "trial-cases/<uuid:trial_case_id>/runs",
        GovernedProcessRunCreateView.as_view(),
        name="trial-process-run-create",
    ),
    path("hmi-profiles", HMIProfileListCreateView.as_view(), name="hmi-profile-list-create"),
    path(
        "hmi-profiles/<uuid:profile_id>",
        HMIProfileDetailView.as_view(),
        name="hmi-profile-detail",
    ),
    path(
        "hmi-profiles/<uuid:profile_id>/actions",
        HMIProfileActionView.as_view(),
        name="hmi-profile-actions",
    ),
    path(
        "process-case-searches",
        ProcessCaseSearchListCreateView.as_view(),
        name="process-case-search-list-create",
    ),
    path(
        "process-case-searches/<uuid:search_id>",
        ProcessCaseSearchDetailView.as_view(),
        name="process-case-search-detail",
    ),
    path("cad-artifacts", CADArtifactListCreateView.as_view(), name="cad-artifact-list-create"),
    path(
        "cad-artifacts/<uuid:artifact_id>",
        CADArtifactDetailView.as_view(),
        name="cad-artifact-detail",
    ),
    path("jobs/<uuid:job_id>", JobDetailView.as_view(), name="job-detail"),
    path("history/analyses", AnalysisHistoryView.as_view(), name="history-analysis-list"),
    path(
        "history/analyses/<str:record_type>/<uuid:record_id>",
        AnalysisDetailView.as_view(),
        name="history-analysis-detail",
    ),
    path("history/jobs", JobHistoryView.as_view(), name="history-job-list"),
    path(
        "history/jobs/<uuid:job_id>",
        JobHistoryDetailView.as_view(),
        name="history-job-detail",
    ),
    path("history/audit-events", AuditHistoryView.as_view(), name="history-audit-list"),
    path(
        "history/audit-events/export",
        AuditExportView.as_view(),
        name="history-audit-export",
    ),
    path(
        "history/audit-events/<uuid:event_id>",
        AuditDetailView.as_view(),
        name="history-audit-detail",
    ),
    path("history/lineage", LineageHistoryView.as_view(), name="history-lineage"),
    path("enterprise/policy", EnterprisePolicyView.as_view(), name="enterprise-policy"),
    path(
        "enterprise/import-batches",
        BulkImportListCreateView.as_view(),
        name="enterprise-import-batch-list-create",
    ),
    path(
        "enterprise/import-batches/<uuid:batch_id>",
        BulkImportDetailView.as_view(),
        name="enterprise-import-batch-detail",
    ),
    path(
        "enterprise/bulk-archive",
        BulkArchiveView.as_view(),
        name="enterprise-bulk-archive",
    ),
    path(
        "knowledge-documents",
        KnowledgeDocumentListCreateView.as_view(),
        name="knowledge-document-list-create",
    ),
    path(
        "knowledge-documents/<uuid:document_id>",
        KnowledgeDocumentDetailView.as_view(),
        name="knowledge-document-detail",
    ),
    path(
        "knowledge-documents/<uuid:document_id>/actions",
        KnowledgeDocumentWorkflowView.as_view(),
        name="knowledge-document-actions",
    ),
    path(
        "knowledge-searches",
        KnowledgeSearchListCreateView.as_view(),
        name="knowledge-search-list-create",
    ),
    path(
        "knowledge-searches/<uuid:search_id>",
        KnowledgeSearchDetailView.as_view(),
        name="knowledge-search-detail",
    ),
    path("rule-profiles", RuleProfileGovernanceListView.as_view(), name="rule-profile-list"),
    path(
        "rule-profiles/<uuid:profile_id>",
        RuleProfileDetailView.as_view(),
        name="rule-profile-detail",
    ),
    path(
        "rule-profiles/<uuid:profile_id>/diff",
        RuleProfileDiffView.as_view(),
        name="rule-profile-diff",
    ),
    path(
        "rule-profiles/<uuid:profile_id>/actions",
        RuleProfileWorkflowView.as_view(),
        name="rule-profile-actions",
    ),
    path(
        "rule-profiles/<uuid:profile_id>/validate",
        RuleProfileValidationView.as_view(),
        name="rule-profile-validate",
    ),
    path(
        "rule-profiles/<uuid:profile_id>/impact-preview",
        RuleProfileImpactPreviewView.as_view(),
        name="rule-profile-impact-preview",
    ),
    path("ingestions", IngestionListCreateView.as_view(), name="ingestion-list-create"),
    path("ingestions/<uuid:batch_id>", IngestionDetailView.as_view(), name="ingestion-detail"),
    path("ingestions/<uuid:batch_id>/files", IngestionFileView.as_view(), name="ingestion-files"),
    path(
        "ingestions/<uuid:batch_id>/mapping",
        IngestionMappingView.as_view(),
        name="ingestion-mapping",
    ),
    path(
        "ingestions/<uuid:batch_id>/validate",
        IngestionValidateView.as_view(),
        name="ingestion-validate",
    ),
    path(
        "ingestions/<uuid:batch_id>/issues", IngestionIssuesView.as_view(), name="ingestion-issues"
    ),
    path(
        "ingestions/<uuid:batch_id>/commit", IngestionCommitView.as_view(), name="ingestion-commit"
    ),
    path(
        "ingestions/<uuid:batch_id>/cancel", IngestionCancelView.as_view(), name="ingestion-cancel"
    ),
    path(
        "ingestions/<uuid:batch_id>/reconciliation",
        IngestionReconciliationView.as_view(),
        name="ingestion-reconciliation",
    ),
    path("import-templates/<str:domain>", ImportTemplateView.as_view(), name="import-template"),
    path(
        "design-reviews",
        DesignReviewListCreateView.as_view(),
        name="design-review-list-create",
    ),
    path(
        "design-reviews/<uuid:review_id>",
        DesignReviewDetailView.as_view(),
        name="design-review-detail",
    ),
    path(
        "design-reviews/<uuid:review_id>/findings/<uuid:finding_id>/decisions",
        ReviewFindingDecisionCreateView.as_view(),
        name="review-finding-decision-create",
    ),
    path(
        "similarity-searches",
        SimilaritySearchListCreateView.as_view(),
        name="similarity-search-list-create",
    ),
    path(
        "similarity-searches/<uuid:search_id>",
        SimilaritySearchDetailView.as_view(),
        name="similarity-search-detail",
    ),
    path(
        "artifact-versions/<uuid:artifact_version_id>/download",
        ArtifactVersionDownloadView.as_view(),
        name="artifact-version-download",
    ),
]
